---
- name: create a network for dnsmasq container
  docker_network:
    name: '{{ dnsmasq_network_name }}'
    state: present

- name: create a dnsmasq container
  docker_container:
    name: '{{ dnsmasq_container_name }}'
    image: andyshinn/dnsmasq:2.83
    pull: true
    state: started
    restart_policy: always
    networks_cli_compatible: true
    networks:
      - name: '{{ dnsmasq_network_name }}'
    capabilities:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: --log-facility=- {{ dnsmasq_options }}
